import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'pt' | 'fr' | 'de' | 'zh' | 'ja' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'home.hero.title.where': 'Where',
    'home.hero.title.strategy': 'Strategy',
    'home.hero.title.meets': 'Meets',
    'home.hero.title.luck': 'Luck',
    'home.hero.subtitle': 'A long-term Polygon project designed for sustainability. Hold LBD, earn real MATIC dividends, and join a mythical future.',
    'home.hero.join_presale': 'Join Presale',
    'home.hero.whitepaper': 'Whitepaper',
    'home.hero.audited': 'Audited Contract',
    'home.hero.dividends': 'Instant Dividends',
    'home.hero.price': 'Current Price',
    'home.hero.dividends_paid': 'Dividends Paid',
    'home.hero.supply': 'Total Supply',
    'home.hero.presale_live': 'Presale Phase {phase} Live',
    'home.presale.title': 'Join the Revolution',
    'home.presale.subtitle': 'Secure your LBD tokens now at the lowest possible price before the public launch.',
    'home.what_is.title': 'What is Lubdan?',
    'home.what_is.desc1': 'Lubdan (LBD) is a premium investment platform built on the Polygon network. Unlike typical meme tokens, Lubdan is designed for sustainability and real yield.',
    'home.what_is.desc2': 'Holders earn automatic MATIC dividends generated from our casino profits, secured by a fully transparent, on-chain mechanism. It\'s where ancient luck meets modern strategy.',
    'home.newsletter.title': 'Stay Updated',
    'home.newsletter.subtitle': 'Subscribe to our newsletter to receive the latest updates about Lubdan, presale phases, and exclusive opportunities.',
    'home.newsletter.placeholder': 'Enter your email address',
    'home.newsletter.subscribe': 'Subscribe',
    'home.newsletter.privacy': 'We respect your privacy. Unsubscribe at any time.',
    'home.features.title': 'Why Choose Lubdan?',
    'home.features.subtitle': 'Built for serious investors who value transparency, sustainability, and real yield over hype.',
    'home.features.yield.title': 'Real Yield Dividends',
    'home.features.yield.desc': 'Hold LBD for 30 days to unlock claimable MATIC dividends generated from our casino profits. Fully automated on-chain.',
    'home.features.secure.title': 'Transparent & Secure',
    'home.features.secure.desc': 'All contracts are verified on Polygonscan. Liquidity is locked, and team tokens are vested linearly over 10 months.',
    'home.features.deflationary.title': 'Deflationary Mechanics',
    'home.features.deflationary.desc': 'Strategic buybacks and burns from casino revenue ensure long-term value appreciation for holders.',
    'faq.title': 'Frequently Asked',
    'nav.home': 'Home',
    'nav.presale': 'Presale',
    'nav.dashboard': 'Dashboard',
    'nav.dividends': 'Dividends',
    'nav.roadmap': 'Roadmap',
    'nav.faq': 'FAQ',
    'nav.whitepaper': 'Whitepaper',
    'nav.connect_wallet': 'Connect Wallet',
    'footer.description': 'Where Strategy Meets Luck. A long-term Polygon project designed for sustainability, transparency, and real MATIC dividends.',
    'footer.quick_links': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.copyright': '© {year} Lubdan Token. All rights reserved.',
    'footer.powered': 'Powered by Polygon',
    'footer.running': 'Running on Mainnet',
    'footer.audit': 'Audit Report',
    'dashboard.eligible': 'Eligible',
    'presale.phase1': 'Phase 1',
    'presale.phase2': 'Phase 2',
    'presale.current': 'Current',
    'presale.widget.connect_first': 'Please connect your wallet first',
    'presale.widget.error': 'Error processing transaction',
    'presale.widget.success': 'Transaction successful',
    'presale.widget.valid_amount': 'Please enter a valid amount',
  },
  pt: {
    'home.hero.title.where': 'Onde',
    'home.hero.title.strategy': 'Estratégia',
    'home.hero.title.meets': 'Encontra',
    'home.hero.title.luck': 'Sorte',
    'home.hero.subtitle': 'Um projeto Polygon de longo prazo projetado para sustentabilidade. Mantenha LBD, ganhe dividendos MATIC reais e junte-se a um futuro mítico.',
    'home.hero.join_presale': 'Participar da Pré-venda',
    'home.hero.whitepaper': 'Whitepaper',
    'home.hero.audited': 'Contrato Auditado',
    'home.hero.dividends': 'Dividendos Instantâneos',
    'home.hero.price': 'Preço Atual',
    'home.hero.dividends_paid': 'Dividendos Pagos',
    'home.hero.supply': 'Fornecimento Total',
    'home.hero.presale_live': 'Fase de Pré-venda {phase} Ao Vivo',
    'home.presale.title': 'Junte-se à Revolução',
    'home.presale.subtitle': 'Garanta seus tokens LBD agora pelo preço mais baixo possível antes do lançamento público.',
    'home.what_is.title': 'O que é Lubdan?',
    'home.what_is.desc1': 'Lubdan (LBD) é uma plataforma de investimento premium construída na rede Polygon. Ao contrário dos tokens meme típicos, Lubdan foi projetado para sustentabilidade e rendimento real.',
    'home.what_is.desc2': 'Os detentores ganham dividendos MATIC automáticos gerados pelos nossos lucros de cassino, garantidos por um mecanismo totalmente transparente e na cadeia. É onde a sorte antiga encontra a estratégia moderna.',
    'home.newsletter.title': 'Mantenha-se Atualizado',
    'home.newsletter.subtitle': 'Inscreva-se em nosso boletim informativo para receber as últimas atualizações sobre Lubdan, fases de pré-venda e oportunidades exclusivas.',
    'home.newsletter.placeholder': 'Digite seu endereço de email',
    'home.newsletter.subscribe': 'Inscrever-se',
    'home.newsletter.privacy': 'Respeitamos sua privacidade. Desinscrever-se a qualquer momento.',
    'home.features.title': 'Por que escolher Lubdan?',
    'home.features.subtitle': 'Construído para investidores sérios que valorizam transparência, sustentabilidade e rendimento real em vez de hype.',
    'home.features.yield.title': 'Dividendos de Rendimento Real',
    'home.features.yield.desc': 'Mantenha LBD por 30 dias para desbloquear dividendos MATIC exigíveis gerados pelos nossos lucros de cassino. Totalmente automatizado na cadeia.',
    'home.features.secure.title': 'Transparente e Seguro',
    'home.features.secure.desc': 'Todos os contratos são verificados no Polygonscan. A liquidez está bloqueada e os tokens da equipe são investidos linearmente ao longo de 10 meses.',
    'home.features.deflationary.title': 'Mecânica Deflacionária',
    'home.features.deflationary.desc': 'Recompras estratégicas e queimas da receita do cassino garantem apreciação de valor de longo prazo para os detentores.',
    'faq.title': 'Perguntas Frequentes',
    'nav.home': 'Início',
    'nav.presale': 'Pré-venda',
    'nav.dashboard': 'Painel',
    'nav.dividends': 'Dividendos',
    'nav.roadmap': 'Roteiro',
    'nav.faq': 'Perguntas Frequentes',
    'nav.whitepaper': 'Whitepaper',
    'nav.connect_wallet': 'Conectar Carteira',
    'footer.description': 'Onde a Estratégia Encontra a Sorte. Um projeto Polygon de longo prazo projetado para sustentabilidade, transparência e dividendos MATIC reais.',
    'footer.quick_links': 'Links Rápidos',
    'footer.resources': 'Recursos',
    'footer.copyright': '© {year} Lubdan Token. Todos os direitos reservados.',
    'footer.powered': 'Powered by Polygon',
    'footer.running': 'Executando na Mainnet',
    'footer.audit': 'Relatório de Auditoria',
    'dashboard.eligible': 'Elegível',
    'presale.phase1': 'Fase 1',
    'presale.phase2': 'Fase 2',
    'presale.current': 'Atual',
    'presale.widget.connect_first': 'Por favor, conecte sua carteira primeiro',
    'presale.widget.error': 'Erro ao processar transação',
    'presale.widget.success': 'Transação bem-sucedida',
    'presale.widget.valid_amount': 'Por favor, insira um valor válido',
  },
  fr: {
    'home.hero.title.where': 'Où',
    'home.hero.title.strategy': 'Stratégie',
    'home.hero.title.meets': 'Rencontre',
    'home.hero.title.luck': 'Chance',
    'home.hero.subtitle': 'Un projet Polygon à long terme conçu pour la durabilité. Conservez LBD, gagnez de vrais dividendes MATIC et rejoignez un avenir mythique.',
    'home.hero.join_presale': 'Rejoindre la Prévente',
    'home.hero.whitepaper': 'Livre Blanc',
    'home.hero.audited': 'Contrat Audité',
    'home.hero.dividends': 'Dividendes Instantanés',
    'home.hero.price': 'Prix Actuel',
    'home.hero.dividends_paid': 'Dividendes Payés',
    'home.hero.supply': 'Offre Totale',
    'home.hero.presale_live': 'Phase de Prévente {phase} En Direct',
    'home.presale.title': 'Rejoignez la Révolution',
    'home.presale.subtitle': 'Sécurisez vos jetons LBD maintenant au prix le plus bas possible avant le lancement public.',
    'home.what_is.title': 'Qu\'est-ce que Lubdan?',
    'home.what_is.desc1': 'Lubdan (LBD) est une plateforme d\'investissement premium construite sur le réseau Polygon. Contrairement aux jetons meme typiques, Lubdan est conçu pour la durabilité et le rendement réel.',
    'home.what_is.desc2': 'Les détenteurs gagnent des dividendes MATIC automatiques générés par nos bénéfices de casino, sécurisés par un mécanisme entièrement transparent et en chaîne. C\'est là que la chance ancienne rencontre la stratégie moderne.',
    'home.newsletter.title': 'Restez à Jour',
    'home.newsletter.subtitle': 'Abonnez-vous à notre newsletter pour recevoir les dernières mises à jour sur Lubdan, les phases de prévente et les opportunités exclusives.',
    'home.newsletter.placeholder': 'Entrez votre adresse e-mail',
    'home.newsletter.subscribe': 'S\'abonner',
    'home.newsletter.privacy': 'Nous respectons votre vie privée. Désinscrivez-vous à tout moment.',
    'home.features.title': 'Pourquoi choisir Lubdan?',
    'home.features.subtitle': 'Construit pour les investisseurs sérieux qui valorisent la transparence, la durabilité et le rendement réel plutôt que le battage médiatique.',
    'home.features.yield.title': 'Dividendes de Rendement Réel',
    'home.features.yield.desc': 'Conservez LBD pendant 30 jours pour débloquer les dividendes MATIC réclamables générés par nos bénéfices de casino. Entièrement automatisé en chaîne.',
    'home.features.secure.title': 'Transparent et Sécurisé',
    'home.features.secure.desc': 'Tous les contrats sont vérifiés sur Polygonscan. La liquidité est bloquée et les jetons de l\'équipe sont investis linéairement sur 10 mois.',
    'home.features.deflationary.title': 'Mécanique Déflationniste',
    'home.features.deflationary.desc': 'Les rachats stratégiques et les brûlures des revenus du casino garantissent une appréciation de la valeur à long terme pour les détenteurs.',
    'faq.title': 'Questions Fréquemment Posées',
    'nav.home': 'Accueil',
    'nav.presale': 'Prévente',
    'nav.dashboard': 'Tableau de Bord',
    'nav.dividends': 'Dividendes',
    'nav.roadmap': 'Feuille de Route',
    'nav.faq': 'FAQ',
    'nav.whitepaper': 'Livre Blanc',
    'nav.connect_wallet': 'Connecter le Portefeuille',
    'footer.description': 'Où la Stratégie Rencontre la Chance. Un projet Polygon à long terme conçu pour la durabilité, la transparence et les vrais dividendes MATIC.',
    'footer.quick_links': 'Liens Rapides',
    'footer.resources': 'Ressources',
    'footer.copyright': '© {year} Lubdan Token. Tous droits réservés.',
    'footer.powered': 'Powered by Polygon',
    'footer.running': 'Exécution sur Mainnet',
    'footer.audit': 'Rapport d\'Audit',
    'dashboard.eligible': 'Éligible',
    'presale.phase1': 'Phase 1',
    'presale.phase2': 'Phase 2',
    'presale.current': 'Actuel',
    'presale.widget.connect_first': 'Veuillez d\'abord connecter votre portefeuille',
    'presale.widget.error': 'Erreur lors du traitement de la transaction',
    'presale.widget.success': 'Transaction réussie',
    'presale.widget.valid_amount': 'Veuillez entrer un montant valide',
  },
  de: {
    'home.hero.title.where': 'Wo',
    'home.hero.title.strategy': 'Strategie',
    'home.hero.title.meets': 'Trifft',
    'home.hero.title.luck': 'Glück',
    'home.hero.subtitle': 'Ein langfristiges Polygon-Projekt für Nachhaltigkeit. Halten Sie LBD, verdienen Sie echte MATIC-Dividenden und treten Sie einer mythischen Zukunft bei.',
    'home.hero.join_presale': 'Zum Vorverkauf Beitreten',
    'home.hero.whitepaper': 'Whitepaper',
    'home.hero.audited': 'Geprüfter Vertrag',
    'home.hero.dividends': 'Sofortige Dividenden',
    'home.hero.price': 'Aktueller Preis',
    'home.hero.dividends_paid': 'Gezahlte Dividenden',
    'home.hero.supply': 'Gesamtangebot',
    'home.hero.presale_live': 'Vorverkaufsphase {phase} Live',
    'home.presale.title': 'Treten Sie der Revolution Bei',
    'home.presale.subtitle': 'Sichern Sie sich jetzt LBD-Token zum niedrigstmöglichen Preis vor dem öffentlichen Start.',
    'home.what_is.title': 'Was ist Lubdan?',
    'home.what_is.desc1': 'Lubdan (LBD) ist eine Premium-Investitionsplattform auf dem Polygon-Netzwerk. Im Gegensatz zu typischen Meme-Tokens ist Lubdan für Nachhaltigkeit und echte Rendite konzipiert.',
    'home.what_is.desc2': 'Inhaber verdienen automatische MATIC-Dividenden, die aus unseren Casino-Gewinnen generiert werden, gesichert durch einen vollständig transparenten On-Chain-Mechanismus. Hier trifft altes Glück auf moderne Strategie.',
    'home.newsletter.title': 'Bleiben Sie auf dem Laufenden',
    'home.newsletter.subtitle': 'Abonnieren Sie unseren Newsletter, um die neuesten Updates zu Lubdan, Vorverkaufsphasen und exklusiven Möglichkeiten zu erhalten.',
    'home.newsletter.placeholder': 'Geben Sie Ihre E-Mail-Adresse ein',
    'home.newsletter.subscribe': 'Abonnieren',
    'home.newsletter.privacy': 'Wir respektieren Ihre Privatsphäre. Jederzeit abmelden.',
    'home.features.title': 'Warum Lubdan Wählen?',
    'home.features.subtitle': 'Gebaut für ernsthafte Investoren, die Transparenz, Nachhaltigkeit und echte Rendite statt Hype schätzen.',
    'home.features.yield.title': 'Echte Rendite-Dividenden',
    'home.features.yield.desc': 'Halten Sie LBD 30 Tage lang, um einlösbare MATIC-Dividenden freizuschalten, die aus unseren Casino-Gewinnen generiert werden. Vollständig automatisiert auf der Kette.',
    'home.features.secure.title': 'Transparent und Sicher',
    'home.features.secure.desc': 'Alle Verträge werden auf Polygonscan überprüft. Liquidität ist gesperrt und Team-Token werden über 10 Monate linear investiert.',
    'home.features.deflationary.title': 'Deflationäre Mechanik',
    'home.features.deflationary.desc': 'Strategische Rückkaufe und Verbrennungen aus Casino-Einnahmen gewährleisten langfristige Wertsteigerung für Inhaber.',
    'faq.title': 'Häufig Gestellte Fragen',
    'nav.home': 'Startseite',
    'nav.presale': 'Vorverkauf',
    'nav.dashboard': 'Dashboard',
    'nav.dividends': 'Dividenden',
    'nav.roadmap': 'Roadmap',
    'nav.faq': 'Häufig Gestellte Fragen',
    'nav.whitepaper': 'Whitepaper',
    'nav.connect_wallet': 'Brieftasche Verbinden',
    'footer.description': 'Wo Strategie auf Glück trifft. Ein langfristiges Polygon-Projekt für Nachhaltigkeit, Transparenz und echte MATIC-Dividenden.',
    'footer.quick_links': 'Schnelllinks',
    'footer.resources': 'Ressourcen',
    'footer.copyright': '© {year} Lubdan Token. Alle Rechte vorbehalten.',
    'footer.powered': 'Powered by Polygon',
    'footer.running': 'Läuft auf Mainnet',
    'footer.audit': 'Audit-Bericht',
    'dashboard.eligible': 'Berechtigt',
    'presale.phase1': 'Phase 1',
    'presale.phase2': 'Phase 2',
    'presale.current': 'Aktuell',
    'presale.widget.connect_first': 'Bitte verbinden Sie zuerst Ihre Brieftasche',
    'presale.widget.error': 'Fehler bei der Transaktionsverarbeitung',
    'presale.widget.success': 'Transaktion erfolgreich',
    'presale.widget.valid_amount': 'Bitte geben Sie einen gültigen Betrag ein',
  },
  zh: {
    'home.hero.title.where': '何处',
    'home.hero.title.strategy': '策略',
    'home.hero.title.meets': '相遇',
    'home.hero.title.luck': '运气',
    'home.hero.subtitle': '为可持续性而设计的长期 Polygon 项目。持有 LBD，赚取真实 MATIC 股息，加入神话般的未来。',
    'home.hero.join_presale': '加入预售',
    'home.hero.whitepaper': '白皮书',
    'home.hero.audited': '已审计合约',
    'home.hero.dividends': '即时股息',
    'home.hero.price': '当前价格',
    'home.hero.dividends_paid': '支付的股息',
    'home.hero.supply': '总供应量',
    'home.hero.presale_live': '预売第 {phase} 阶段直播',
    'home.presale.title': '加入革命',
    'home.presale.subtitle': '现在以最低价格购买 LBD 代币，在公开发布前获得保障。',
    'home.what_is.title': '什么是 Lubdan？',
    'home.what_is.desc1': 'Lubdan (LBD) 是建立在 Polygon 网络上的高级投资平台。与典型的模因代币不同，Lubdan 为可持续性和真实收益而设计。',
    'home.what_is.desc2': '持有者从我们的赌场利润中获得自动 MATIC 股息，由完全透明的链上机制保障。这是古老的运气与现代策略的相遇。',
    'home.newsletter.title': '保持更新',
    'home.newsletter.subtitle': '订阅我们的新闻通讯，获取有关 Lubdan、预售阶段和独家机会的最新更新。',
    'home.newsletter.placeholder': '输入您的电子邮件地址',
    'home.newsletter.subscribe': '订阅',
    'home.newsletter.privacy': '我们尊重您的隐私。随时取消订阅。',
    'home.features.title': '为什么选择 Lubdan？',
    'home.features.subtitle': '为重视透明度、可持续性和真实收益而非炒作的认真投资者而建。',
    'home.features.yield.title': '真实收益股息',
    'home.features.yield.desc': '持有 LBD 30 天以解锁从我们的赌场利润生成的可领取 MATIC 股息。完全自动化链上。',
    'home.features.secure.title': '透明且安全',
    'home.features.secure.desc': '所有合约都在 Polygonscan 上验证。流动性被锁定，团队代币在 10 个月内线性投资。',
    'home.features.deflationary.title': '通缩机制',
    'home.features.deflationary.desc': '来自赌场收入的战略性回购和销毁确保持有人的長期价值上涨。',
    'faq.title': '常见问题',
    'nav.home': '首页',
    'nav.presale': '预售',
    'nav.dashboard': '仪表板',
    'nav.dividends': '股息',
    'nav.roadmap': '路线图',
    'nav.faq': '常见问题',
    'nav.whitepaper': '白皮书',
    'nav.connect_wallet': '连接钱包',
    'footer.description': '策略与运气相遇的地方。为可持续性、透明度和真实 MATIC 股息而设计的长期 Polygon 项目。',
    'footer.quick_links': '快速链接',
    'footer.resources': '资源',
    'footer.copyright': '© {year} Lubdan 代币。版权所有。',
    'footer.powered': 'Powered by Polygon',
    'footer.running': '在主网上运行',
    'footer.audit': '审计报告',
    'dashboard.eligible': '符合条件',
    'presale.phase1': '第 1 阶段',
    'presale.phase2': '第 2 阶段',
    'presale.current': '当前',
    'presale.widget.connect_first': '请先连接您的钱包',
    'presale.widget.error': '处理交易时出错',
    'presale.widget.success': '交易成功',
    'presale.widget.valid_amount': '请输入有效金额',
  },
  ja: {
    'home.hero.title.where': 'どこで',
    'home.hero.title.strategy': '戦略',
    'home.hero.title.meets': '出会う',
    'home.hero.title.luck': '運',
    'home.hero.subtitle': '持続可能性のために設計された長期 Polygon プロジェクト。LBD を保有し、実際の MATIC 配当を獲得し、神話的な未来に参加してください。',
    'home.hero.join_presale': 'プレセールに参加',
    'home.hero.whitepaper': 'ホワイトペーパー',
    'home.hero.audited': '監査済みコントラクト',
    'home.hero.dividends': '即座の配当',
    'home.hero.price': '現在の価格',
    'home.hero.dividends_paid': '支払われた配当',
    'home.hero.supply': '総供給量',
    'home.hero.presale_live': 'プレセール第 {phase} 段階ライブ',
    'home.presale.title': '革命に参加',
    'home.presale.subtitle': '公開前に最低価格で LBD トークンを今すぐ確保してください。',
    'home.what_is.title': 'Lubdan とは？',
    'home.what_is.desc1': 'Lubdan (LBD) は Polygon ネットワーク上に構築されたプレミアム投資プラットフォームです。典型的なミームトークンとは異なり、Lubdan は持続可能性と実際の利回りのために設計されています。',
    'home.what_is.desc2': 'ホルダーはカジノの利益から生成された自動 MATIC 配当を獲得し、完全に透明なオンチェーン メカニズムによって保護されます。ここは古い運と現代的な戦略が出会う場所です。',
    'home.newsletter.title': '最新情報を入手',
    'home.newsletter.subtitle': 'ニュースレターを購読して、Lubdan、プレセール段階、および独占的な機会に関する最新の更新を受け取ります。',
    'home.newsletter.placeholder': 'メールアドレスを入力してください',
    'home.newsletter.subscribe': '購読',
    'home.newsletter.privacy': 'プライバシーを尊重します。いつでも登録解除できます。',
    'home.features.title': 'Lubdan を選ぶ理由？',
    'home.features.subtitle': '透明性、持続可能性、誇大広告ではなく実際の利回りを重視する真摯な投資家向けに構築されています。',
    'home.features.yield.title': '実際の利回り配当',
    'home.features.yield.desc': '30 日間 LBD を保有して、カジノの利益から生成された請求可能な MATIC 配当をアンロックします。完全に自動化されたオンチェーン。',
    'home.features.secure.title': '透明で安全',
    'home.features.secure.desc': 'すべてのコントラクトは Polygonscan で検証されています。流動性はロックされ、チームトークンは 10 か月間線形に投資されます。',
    'home.features.deflationary.title': 'デフレメカニズム',
    'home.features.deflationary.desc': 'カジノ収益からの戦略的な買い戻しと焼殱により、ホルダーの長期的な価値上昇を保証します。',
    'faq.title': 'よくあるご質問',
    'nav.home': 'ホーム',
    'nav.presale': 'プレセール',
    'nav.dashboard': 'ダッシュボード',
    'nav.dividends': '配当',
    'nav.roadmap': 'ロードマップ',
    'nav.faq': 'よくある質問',
    'nav.whitepaper': 'ホワイトペーパー',
    'nav.connect_wallet': 'ウォレットを接続',
    'footer.description': '戦略と運が出会う場所。持続可能性、透明性、実際の MATIC 配当のために設計された長期 Polygon プロジェクト。',
    'footer.quick_links': 'クイックリンク',
    'footer.resources': 'リソース',
    'footer.copyright': '© {year} Lubdan トークン。著作権所有。',
    'footer.powered': 'Powered by Polygon',
    'footer.running': 'メインネットで実行中',
    'footer.audit': '監査レポート',
    'dashboard.eligible': '適格',
    'presale.phase1': '第 1 段階',
    'presale.phase2': '第 2 段階',
    'presale.current': '現在',
    'presale.widget.connect_first': 'まず、ウォレットを接続してください',
    'presale.widget.error': 'トランザクション処理中にエラーが発生しました',
    'presale.widget.success': 'トランザクション成功',
    'presale.widget.valid_amount': '有効な金額を入力してください',
  },
  ko: {
    'home.hero.title.where': '어디서',
    'home.hero.title.strategy': '전략',
    'home.hero.title.meets': '만나다',
    'home.hero.title.luck': '행운',
    'home.hero.subtitle': '지속 가능성을 위해 설계된 장기 Polygon 프로젝트입니다. LBD를 보유하고 실제 MATIC 배당금을 얻고 신화적인 미래에 참여하세요.',
    'home.hero.join_presale': '사전판매 참여',
    'home.hero.whitepaper': '백서',
    'home.hero.audited': '감사된 계약',
    'home.hero.dividends': '즉시 배당금',
    'home.hero.price': '현재 가격',
    'home.hero.dividends_paid': '지급된 배당금',
    'home.hero.supply': '총 공급률',
    'home.hero.presale_live': '사전판매 단계 {phase} 라이브',
    'home.presale.title': '혁명에 참여하세요',
    'home.presale.subtitle': '공개 출시 전에 지금 가장 낮은 가격으로 LBD 토큰을 확보하세요.',
    'home.what_is.title': 'Lubdan이란?',
    'home.what_is.desc1': 'Lubdan (LBD)은 Polygon 네트워크에 구축된 프리미엄 투자 플래폰입니다. 일반적인 밌 토큰과 달리 Lubdan은 지속 가능성과 실제 수익을 위해 설계되었습니다.',
    'home.what_is.desc2': '보유자는 카지노 수익에서 생성된 자동 MATIC 배당금을 얻으며 완전히 투명c한 온체인 메커니즘으로 보호됩니다. 이것은 고대의 행운이 현대 전략을 만나는 곳입니다.',
    'home.newsletter.title': '최신 정보 유지',
    'home.newsletter.subtitle': '뉴스레터를 구독하여 Lubdan, 사전판매 단계 및 독점 기회에 대한 최신 업데이트를 받으세요.',
    'home.newsletter.placeholder': '이메일 주소를 입력하세요',
    'home.newsletter.subscribe': '구독',
    'home.newsletter.privacy': '개인정보를 존중합니다. 언제든지 구독을 취소할 수 있습니다.',
    'home.features.title': 'Lubdan을 선택하는 이유?',
    'home.features.subtitle': '투명c성, 지속 가능성 및 과대 광고가 아닌 실제 수익을 중시하는 진지한 투자자를 위해 구축되었습니다.',
    'home.features.yield.title': '실제 수익 배당금',
    'home.features.yield.desc': '30일 동안 LBD를 보유하여 카지노 수익에서 생성된 청구 가능한 MATIC 배당금을 잠금 해제하세요. 완전히 자동화된 온체인.',
    'home.features.secure.title': '투명c하고 안전함',
    'home.features.secure.desc': '모든 계약은 Polygonscan에서 검증됩니다. 유동성이 잠결 있고 팀 토큰은 10개월에 걸쳐 선형으로 투자됩니다.',
    'home.features.deflationary.title': '디플레이션 메커니즘',
    'home.features.deflationary.desc': '카지노 수익의 전략적 환매 및 소각으로 보유자의 장기 가치 상승을 보장합니다.',
    'faq.title': '자주 묻는 질문',
    'nav.home': '홈',
    'nav.presale': '사전판매',
    'nav.dashboard': '대시보드',
    'nav.dividends': '배당금',
    'nav.roadmap': '로드매',
    'nav.faq': '자주 묻는 질문',
    'nav.whitepaper': '백서',
    'nav.connect_wallet': '지갑 연결',
    'footer.description': '전략과 행운이 만나는 곳입니다. 지속 가능성, 투명c성 및 실제 MATIC 배당금을 위해 설계된 장기 Polygon 프로젝트입니다.',
    'footer.quick_links': '빠른 링크',
    'footer.resources': '리소스',
    'footer.copyright': '© {year} Lubdan 토큰. 판권소유.',
    'footer.powered': 'Powered by Polygon',
    'footer.running': '메인넷에서 실행 중',
    'footer.audit': '감사 보고서',
    'dashboard.eligible': '적격',
    'presale.phase1': '1단계',
    'presale.phase2': '2단계',
    'presale.current': '현재',
    'presale.widget.connect_first': '먼저 지갑을 연결하세요',
    'presale.widget.error': '거래 처리 중 오류 발생',
    'presale.widget.success': '거래 성공',
    'presale.widget.valid_amount': '유효한 금액을 입력하세요',
  },
};

function detectLanguage(): Language {
  // Get user's browser language
  const browserLang = navigator.language.toLowerCase();
  
  // Map browser language codes to supported languages
  const langMap: Record<string, Language> = {
    'pt': 'pt',
    'pt-br': 'pt',
    'pt-pt': 'pt',
    'fr': 'fr',
    'fr-fr': 'fr',
    'de': 'de',
    'de-de': 'de',
    'zh': 'zh',
    'zh-cn': 'zh',
    'zh-hans': 'zh',
    'ja': 'ja',
    'ja-jp': 'ja',
    'ko': 'ko',
    'ko-kr': 'ko',
  };

  // Try exact match first
  if (langMap[browserLang]) {
    return langMap[browserLang];
  }

  // Try language code only (first 2 chars)
  const langCode = browserLang.substring(0, 2);
  if (langMap[langCode]) {
    return langMap[langCode];
  }

  // Default to English
  return 'en';
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check localStorage first
    const saved = localStorage.getItem('lubdan-language');
    if (saved && (translations[saved as Language])) {
      return saved as Language;
    }
    // Detect from browser
    return detectLanguage();
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lubdan-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
